# Generated by Django 6.0.3 on 2026-03-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(max_length=10),
        ),
    ]
