# Generated by Django 6.0.3 on 2026-03-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0003_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
