# Generated by Django 6.0.3 on 2026-03-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0004_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(max_length=100),
        ),
    ]
