# Generated by Django 6.0.3 on 2026-03-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0006_alter_user_country_alter_user_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
