# Generated by Django 6.0.3 on 2026-03-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0007_user_profile_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_img",
        ),
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.ImageField(default=" ", upload_to="profile/"),
        ),
    ]
