# Generated by Django 6.0.3 on 2026-03-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0008_remove_user_profile_img_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(default=" ", upload_to="profile_img/"),
        ),
    ]
