# Generated by Django 6.0.3 on 2026-03-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0009_remove_user_profile_user_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profile_img/"),
        ),
    ]
