# Generated by Django 6.0.3 on 2026-04-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0010_alter_user_country_alter_user_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="Customer", max_length=15),
        ),
    ]
