# Generated by Django 6.0.3 on 2026-04-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0011_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="add_tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="customer", max_length=15),
        ),
    ]
