# Generated by Django 6.0.3 on 2026-04-12 02:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0012_add_tour_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="destinations/")),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("international", "International"),
                        ],
                        default="national",
                        max_length=20,
                    ),
                ),
                (
                    "tour_type",
                    models.CharField(
                        choices=[
                            ("weekend", "Weekend Tour"),
                            ("holiday", "Holiday Tour"),
                            ("family", "Family Tour"),
                            ("beach", "Beach Tour"),
                            ("adventure", "Adventure Tour"),
                            ("honeymoon", "Honeymoon Tour"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "duration_days",
                    models.PositiveIntegerField(help_text="Number of days"),
                ),
                (
                    "duration_nights",
                    models.PositiveIntegerField(help_text="Number of nights"),
                ),
                ("max_persons", models.PositiveIntegerField(default=10)),
                ("min_persons", models.PositiveIntegerField(default=1)),
                (
                    "price_per_person",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("image", models.ImageField(upload_to="tours/")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tours",
                        to="travelapp.destination",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travelapp.user"
                    ),
                ),
            ],
        ),
    ]
